### ISSUE TITLE
What kind of algorithms do you use ?

### ISSUE THREAD

**Issue by Ostnie** [Merle314/FacePoseEstimation#2]
I have used your code for pose estimation some times and it works well ,I want to know the algorithms you use ,could you please tell me ?
Besides this , when you use dlib for landmark detect , which points do you use for calculations? When I use opencv I know it used 5 points to get the result , How about your code ?
Many thanks !

**Comment by Merle314** [comment]
I used Weak perspective projection principle，and used Least-squares algorithm to fit the 68 Feature Points detected by dlib and the standard position of the 68 Face Feature Point.

**Comment by Ostnie** [comment]
@Merle314 I found a paper Optimum Fiducials Under Weak Perspective Projection in your code ,but I can’t combine your code with the  formula in this paper， I don't know if you have made a change or I didn't find the position in the paper. Could you please point out the formulas for me ? I know it is wrong to ask you for paper details, but I really have a try and don't find the correct formulas.

**Comment by Merle314** [comment]
@Ostnie I mainly used "3.1. 3-D Fiducials" part of that paper. And i added some English notes for you to understand. Most importantly, transelate the Rotation matrix to the Rotation angle, the formula is like this http://planning.cs.uiuc.edu/node102.html, is very easy to calculate the rotation angle. You can point out perticular place where you don't understand.
